# Generated by Django 5.0.6 on 2024-06-28 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('nombre_autor', models.CharField(default='no posee autor', max_length=50)),
                ('foto', models.ImageField(null=True, upload_to='libros', verbose_name='Imagen')),
                ('precio', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('best_seler', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('No_Ficción', 'No_Ficción'), ('Sin tipo', 'Sin tipo'), ('Ficción', 'Ficción')], default='Sin tipo', max_length=30)),
                ('subtipo', models.CharField(choices=[('Ficción', [('Sci-fi', 'Sci-fi'), ('Misterio', 'Misterio'), ('Terror', 'Terror')]), ('No_Ficción', [('Historia', 'Historia'), ('Biografía', 'Biografía')]), ('Sin subtipo', 'Sin Subtipo')], default='Sin subtipo', max_length=40)),
            ],
        ),
    ]
