# Generated by Django 5.0.6 on 2024-06-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='tipo',
            field=models.CharField(choices=[('Ficción', 'Ficción'), ('Sin tipo', 'Sin tipo'), ('No_Ficción', 'No_Ficción')], default='Sin tipo', max_length=30),
        ),
    ]
