# Generated by Django 5.0.6 on 2024-06-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0002_alter_libro_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='tipo',
            field=models.CharField(choices=[('No_Ficción', 'No_Ficción'), ('Ficción', 'Ficción'), ('Sin tipo', 'Sin tipo')], default='Sin tipo', max_length=30),
        ),
    ]
