# Generated by Django 5.0.6 on 2024-06-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0004_alter_libro_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='tipo',
            field=models.CharField(choices=[('Sin tipo', 'Sin tipo'), ('Ficción', 'Ficción'), ('No_Ficción', 'No_Ficción')], default='Sin tipo', max_length=30),
        ),
    ]
