# Generated by Django 5.0.6 on 2024-06-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0007_alter_libro_tipo_compra_compraitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraitem',
            name='estado',
            field=models.CharField(choices=[('Entregado', 'Entregado'), ('En camino', 'En camino'), ('Preparando', 'Preparando')], default='Preparando', max_length=40),
        ),
        migrations.AlterField(
            model_name='libro',
            name='tipo',
            field=models.CharField(choices=[('No_Ficción', 'No_Ficción'), ('Sin tipo', 'Sin tipo'), ('Ficción', 'Ficción')], default='Sin tipo', max_length=30),
        ),
    ]
